[plugin]
repository = "https://github.com/NotNite/OfDungeonsDeep.git"
commit = "24aecbc5b3f789f34aeb57b11d99137a8805b6c7"
owners = ["NotNite", "MidoriKami", "MKhayle"]
project_path = "OfDungeonsDeep"
changelog = """
- API 12 update
"""
