[plugin]
repository = "https://github.com/NotNite/OfDungeonsDeep.git"
commit = "ccc59592b15c5837759dca44a3470351b7447296"
owners = ["NotNite", "MidoriKami", "MKhayle"]
project_path = "OfDungeonsDeep"
changelog = """
- API 12 update
"""
