[plugin]
repository = 'https://github.com/MKhayle/TheHeartOfTheParty.git'
commit = 'b0838de092b426991c7242c3d638ccf8e84eb8bb'
owners = [ 'anna-is-cute', 'MKhayle' ]
changelog = 'API12 update. Added a Main UI callback so it can be used with Wotsit!'
