[plugin]
repository = 'https://github.com/MKhayle/TheHeartOfTheParty.git'
commit = 'f95465518bd843cffd3e8578e455a0c4e015a1dc'
owners = [ 'anna-is-cute', 'MKhayle' ]
changelog = 'API12 update. Added a Main UI callback so it can be used with Wotsit!'
